import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Vortex } from "@/components/ui/vortex";
import Navigation from "@/components/navigation";
const inter = Inter();
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Vortex
          backgroundColor="black"
          rangeY={800}
          particleCount={500}
          baseHue={120}
          className="h-screen overflow-hidden">
          <Navigation>
            {children}
          </Navigation>

        </Vortex>

      </body>
    </html>
  );
}
